# Generated by Django 2.1.7 on 2019-02-13 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190213_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 18, 36, 13, 207869, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
